### ISSUE TITLE
Feature: User can view different agents, maps, and weapons 

### ISSUE THREAD

**Issue by timlee712** [timlee712/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for different agents, maps, and weapons

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to navigate to different pages using the search bar, nav bar/dropdown, and the carousel.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="176" alt="issue-1-wireframe-1" src="https://user-images.githubusercontent.com/121835590/221721712-89c9bada-7aca-41ee-bc94-f5182ed7abd6.png">
<img width="289" alt="issue-1-wireframe-2" src="https://user-images.githubusercontent.com/121835590/221721716-d00f3617-7723-4a2d-b6cf-e42252da8303.png">
<img width="153" alt="issue-1-wireframe-3" src="https://user-images.githubusercontent.com/121835590/221721714-5efd5684-405e-4da5-b8e8-d52466d82d70.png">
<img width="136" alt="issue-1-wireframe-4" src="https://user-images.githubusercontent.com/121835590/221721715-24e26d61-6e9f-4998-8cab-ccda8ecf5f8d.png">
<img width="957" alt="issue-1-wireframe-5" src="https://user-images.githubusercontent.com/121835590/221721751-35a6649f-f81e-40ad-adee-005ca85e9fbc.png">
<img width="534" alt="issue-1-wireframe-6" src="https://user-images.githubusercontent.com/121835590/221721753-820d467b-f310-43ff-986d-3e207af81c35.png">
<img width="536" alt="issue-1-wireframe-7" src="https://user-images.githubusercontent.com/121835590/221721754-6496b2d3-aac4-4c35-a561-4d09735e6796.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Complete HTML and CSS
  - [x] Create HTML for the home page
    - [x] Create a navbar in the header to look like the wireframe in figma
    - [x] Create a `div` for the search box that includes the logo, search bar, and a submit `button`
    - [x] Create a `div` for the text content
    - [x] Create a carousel with images
    - [x] Create a search bar under the navbar ONLY for mobile view
  - [x] Style the home page in CSS to look like the wireframe in figma (mobile first)
  - [x] Create the Agents page in HTML
    - [x] Create an `h1` for the title header 'Agents' and add a border-bottom to act as a line break
  - [x] Style the Agents page in CSS to look like the wireframe in figma
  - [x] Create the Maps page in HTML
    - [x] Create an `h1` for the title header 'Maps' and add a border-bottom to act as a line break
  - [x] Style the Maps page in CSS to look like the wireframe in figma
  - [x] Create the Weapons page in HTML
    - [x] Create an `h1` for the title header 'Weapons' and add a border-bottom to act as a line break
  - [x] Style the Weapons page in CSS to look like the wireframe in figma
- [x] Create a JS file
  - [x] Create a timer for the carousel images to change after 5 second intervals
    - [x] Add left and right buttons to go forward or backwards
    - [x] Add circle buttons so that the user can choose exactly which slide they want to view
  - [x] Create a function `viewSwap()` that switches views depending on which tab was clicked
  - [x] Make API request for all agents
      - [x] Loop over all agents and create `div`, `p`, and `img` element to show the portraits of all agents
  - [x] Make API request for all maps
      - [x] Loop over all maps and create `div`, `p`, and `img` element to show the cover image of the maps
  - [x] Make API request for all weapons
      - [x] Loop over all weapons and create `div`, `p`, and  `img` element to show the photos of all weapons
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
