### ISSUE TITLE
Feature: User can search for agents, maps, and weapons and favorite them so that it appears at the top

### ISSUE THREAD

**Issue by timlee712** [timlee712/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for agents, maps, and weapons and favorite them so that it appears at the top
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

This feature allows the user to search for different agents, maps, and weapons as well as, favoriting specific agents, maps, and weapons by clicking the star button.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
<img width="741" alt="Screenshot 2023-03-01 at 12 17 11 PM" src="https://user-images.githubusercontent.com/121835590/222256521-82c52a09-4107-4c7e-9a81-ab0fe029773c.png">
<img width="343" alt="Screenshot 2023-03-01 at 12 18 57 PM" src="https://user-images.githubusercontent.com/121835590/222256531-ae54eafe-b3c8-486c-b864-3ca185b84573.png">
<img width="450" alt="Screenshot 2023-03-01 at 12 19 31 PM" src="https://user-images.githubusercontent.com/121835590/222256552-5204bc5e-9b95-4ab5-8770-6ff7337b7110.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a separate viewSwap for the search results page
  - [x] Style it to look like the wireframe in figma
- [x] Make an API request so that the value of the search bar `input` can be filtered through to find the `displayName` of the agents, maps, and weapons
  - [x] Then create a `a` and `p` elements so that it appears on the `search-results` page
  - [x] The user should be able to click the `a` element which changes the page to the corresponding page using `viewSwap` 
- [x] Create a star icon in the div next the the agent name, map name, and weapon name
  - [x] Style it to look like the wireframe in figma
    - [x] Make the star transparent
    - [x] When user clicks on it the star changes to yellow
  - [x]  Create an addEventListener so that the favorited agents, maps, and weapons appear at the front
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
