### ISSUE TITLE
Feature: User can create agent compositions for maps

### ISSUE THREAD

**Issue by timlee712** [timlee712/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create agent compositions for each map

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to create a new composition, select a map, and add 5 agents to the map.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="360" alt="Screenshot 2023-03-07 at 4 45 41 PM" src="https://user-images.githubusercontent.com/121835590/223589857-02af284c-f82c-454a-b6b9-cb3c3423a7e7.png">
<img width="184" alt="Screenshot 2023-03-07 at 4 42 42 PM" src="https://user-images.githubusercontent.com/121835590/223589641-18e8246e-d807-4f6a-a51d-ad8edb951a41.png">
<img width="536" alt="Screenshot 2023-03-07 at 4 49 13 PM" src="https://user-images.githubusercontent.com/121835590/223590468-bcbee5af-e5c3-4880-bbc9-5568c2bb7bb3.png">
<img width="538" alt="Screenshot 2023-03-07 at 4 49 22 PM" src="https://user-images.githubusercontent.com/121835590/223590508-69852f78-f90c-4c0e-a522-6bfd9e649d60.png">
<img width="536" alt="Screenshot 2023-03-07 at 4 49 42 PM" src="https://user-images.githubusercontent.com/121835590/223590521-ee852ec7-7e55-4783-9655-7fb7f07be89e.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a new view for the agent composition and create new agent composition
- [x] Create a div container for the form
- [x] Create an `select` for the maps
  - [x] When a map is selected the corresponding image should show up
  - [x] XMLHttpRequest for the maps `splash` images
- [x] Create a div for the agents that will be selected
- [x] Create the div for the agent pool
  - [x] XMLHttpRequest for the agent `displayIcons` 
- [x] Create a submit button for the form
  - [x] Add and event listener for the button to submit the form into the localStorage
- [x] Create a new data property to hold the data from the forms
- [x] Add the completed forms to the view agent composition page
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
