### ISSUE TITLE
Feature: User can view agent descriptions, map coordinates, and weapon categories

### ISSUE THREAD

**Issue by timlee712** [timlee712/ajax-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view agent descriptions, map coordinates, and weapon categories

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user hovers over an agent, map, or weapon image, the corresponding description, coordinate, or category will be displayed.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="853" alt="Screenshot 2023-03-09 at 2 02 00 PM" src="https://user-images.githubusercontent.com/121835590/224170992-7101645e-4fab-4318-8608-d7cefb8c7696.png">
<img width="264" alt="Screenshot 2023-03-09 at 2 04 08 PM" src="https://user-images.githubusercontent.com/121835590/224170997-fa2036f6-1bdc-4748-8b0c-282c2f662718.png">
<img width="310" alt="Screenshot 2023-03-09 at 2 18 26 PM" src="https://user-images.githubusercontent.com/121835590/224179174-fa516de8-833c-4078-acbd-2c204b1a16c6.png">
<img width="750" alt="Screenshot 2023-03-09 at 2 23 47 PM" src="https://user-images.githubusercontent.com/121835590/224179181-13f9e7bc-bf61-464a-bf3c-30fecc3c2855.png">
<img width="852" alt="Screenshot 2023-03-09 at 2 55 47 PM" src="https://user-images.githubusercontent.com/121835590/224179195-c0b30d53-833a-4684-8824-120efda9ce21.png">
<img width="425" alt="Screenshot 2023-03-09 at 2 56 16 PM" src="https://user-images.githubusercontent.com/121835590/224179196-5332ead9-6fc3-4f3b-8e73-195e6e18b43c.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create new elements in the `renderAgents()` function for the agent description
  - [x] Create a `p` element for the for the description
    - [x] Give it the class `agent-description`
    - [x] The text inside the `p` element should be `agent.description` from the Valorant API
  - [x] Give a `'mouseover'` event listener for the agent image
    - [x] When 'mouseover' event is fired, the agentDescription will be appended to the agentImageContainer
  - [x] Give a `'mouseout'` event listener for the agent image
    - [x] This time when the 'mouseout' event is fired, the agentDescription will be removed from the agentImageContainer
- [x] Create new elements in the `renderMaps()` function for the map coordinates
  - [x] Create a `p` element for the for the coordinates
    - [x] Give it the class `map-coordinates`
    - [x] The text inside the `p` element should be `map.coordinates` from the Valorant API
  - [x] Give a `'mouseover'` event listener for the map image
    - [x] When 'mouseover' event is fired, the mapCoordinate will be appended to the mapImageContainer
  - [x] Give a `'mouseout'` event listener for the map image
    - [x] This time when the 'mouseout' event is fired, the mapCoordinates will be removed from the mapImageContainer
- [x] Create new elements in the `renderWeapons()` function for the weapon category
  - [x] Create a `p` element for the for the category
    - [x] Give it the class `weapon-category`
    - [x] The text inside the `p` element should be `weapon.shopData.category` from the Valorant API
  - [x] Give a `'mouseover'` event listener for the weapon image
    - [x] When 'mouseover' event is fired, the weaponCategory will be appended to the weaponImageContainer
  - [x] Give a `'mouseout'` event listener for the weapon image
    - [x] This time when the 'mouseout' event is fired, the weaponCategory will be removed from the weaponImageContainer
- [x] Create a back button so the user can view the original agent page again.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
