### ISSUE TITLE
Feature: User can delete agent compositions

### ISSUE THREAD

**Issue by timlee712** [timlee712/ajax-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete agent comps.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks on the delete/trash button, the container holding the agent comps will be deleted. And the data in the localStorage will also be deleted.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="658" alt="Screenshot 2023-03-08 at 10 53 20 AM" src="https://user-images.githubusercontent.com/121835590/223808674-a86c0aa6-8222-468a-8746-881e10a91bc0.png">
<img width="274" alt="Screenshot 2023-03-08 at 10 54 57 AM" src="https://user-images.githubusercontent.com/121835590/223808681-ac34787a-58d6-427b-957d-19d1bb05cba5.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a button element
  - [x] Create an icon element
  - [x] Give the icon element the classes of `fa-solid fa-trash-can`
  - [x] Append the Icon to the Button
  - [x] Append the Button to the container itself so it appears inside
- [x] Style the button to look like the wireframe from figma
- [x] Add a `'click'` event listener for the delete button
  - [x] Remove the container itself so it doesn't appear
  - [x] Splice the composition from `data.agentComps` so that it is cut from the data object 
  - [x] Update the localStorage
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
